config/routes.rb
Calender2::Application.routes.draw do
  get "home" =>"pages#home", :as => :home
  get "calender(/:year(/:month))" => "pages#calender", :as => :calender
  get "pages/contact_us"

 root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def calender
    # Get correct time 
    if (params.has_key?(:year))
      if (params.has_key?(:month))
        @time = DateTime.new(params[:year].to_i,params[:month].to_i)
       else
        @time = DateTime.new(params[:year].to_i)
      end
    else
      @time = DateTime.now()
      @time = DateTime.new(@time.year, @time.month)
    end
    
    #get first day of week
    first_day_of_week = @time.wday + 1
    
    #get last date of month
    @last_date_of_month = Date.new(@time.year, @time.month, -1).day
    
    #strat creating string
    @str = "<tr>"
    #print first week
    i = 1
    dummy_space = 1
    while (dummy_space < first_day_of_week)
      @str += "<td>&nbsp</td>" 
      dummy_space = dummy_space + 1
    end
    while (i <= (8-first_day_of_week))
      @str += "<td>#{i}</td>"
      i = i +1
    end
    @str += "</tr>"
    
    x = 3
    if((i + 28) < @last_date_of_month)
      x = 4
    end
    
    #print rest of week
    x.times do |j|
      @str += "<tr>"
      7.times do |k|
        @str += "<td>#{i}</td>" 
        i = i +1
      end
      @str += "</tr>"
    end   
    1.times do |j|
      @str += "<tr>"
      7.times do |k|
        @str += "<td>#{i}</td>"
        i = i +1
        if (i > @last_date_of_month)
          break
        end
      end
      @str += "</tr>"
    end
    @previous_year = @time.year
    @next_year = @time.year
    @previous_month = @time.month - 1
    @next_month = @time.month + 1
    if (@previous_month < 1)
      @previous_month = 12
      @previous_year -= 1
    end
    if (@next_month > 12)
      @next_month = 1
      @next_year += 1
    end
  end
  
  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calender2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper"><!-- #wrapper -->

	<header><!-- header -->
		<h1><a href="#">Blue Droplet</a></h1>
		<h2>Your unique and compelling tag line goes here</h2>
		<%=image_tag "headerimg.jpg", size: "940*200"%><!-- header image -->
	</header><!-- end of header -->
	
	<nav><!-- top nav -->
		<div class="menu">
			<ul>
				<%=link_to "Home", home_path%>
				<%=link_to "Calender", calender_path%>
			</ul>
		</div>
	</nav><!-- end of top nav -->
	
	<section id="main"><!-- #main content and sidebar area -->
			<section id="content"><!-- #content -->
			
        		<article>
						<%= yield %>
				</article>		
			</section><!-- end of #content -->

		<aside id="sidebar"><!-- sidebar -->
				<h3>Things To Do</h3>
					<ul>
						<li><a href="#">Play Games</a></li>
						<li><a href="#">Chat With Friends</a></li>
						<li><a href="#">Swap Stories</a></li>
						<li><a href="#">Sell Stuff</a></li>
						<li><a href="#">Buy Stuff</a></li>
						<li><a href="#">Trade Stuff</a></li>
					</ul>
					
				<h3>Sponsors</h3>
					<%=image_tag "ad180.png"%><br /><br />

				<h3>Connect With Us</h3>
					<ul>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">LinkedIn</a></li>
						<li><a href="#">Flickr</a></li>
					</ul>

		</aside><!-- end of sidebar -->

	</section><!-- end of #main content and sidebar-->
	
		<footer>
		<section id="footer-area">

			<section id="footer-outer-block">
					<aside class="footer-segment">
							<h4>Friends</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #first footer segment -->

					<aside class="footer-segment">
							<h4>Awesome Stuff</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #second footer segment -->

					<aside class="footer-segment">
							<h4>Coolness</h4>
								<ul>
									<li><a href="#">one linkylink</a></li>
									<li><a href="#">two linkylinks</a></li>
									<li><a href="#">three linkylinks</a></li>
								</ul>
					</aside><!-- end of #third footer segment -->
					
					<aside class="footer-segment">
							<h4>Blahdyblah</h4>
								<p>&copy; 2010 <a href="#">yoursite.com</a> Praesent libero. Sed cursus ante dapibus diam. Sed nisi.</p>
					</aside><!-- end of #fourth footer segment -->

			</section><!-- end of footer-outer-block -->

		</section><!-- end of footer-area -->
	</footer>
	
</div><!-- #wrapper -->
<!-- Free template created by http://freehtml5templates.com -->
</body>
</html>

app/views/pages/calender.html.erb
<%=@time.inspect%> </br>
<%="Day of week #{@time.wday + 1}"%> </br>
<%="Last date of month #{@last_date_of_month}"%> </br>

<%=link_to "<<prev", calender_path(:year => @previous_year, :month => @previous_month)%>
<%=link_to "next>>", calender_path(:year => @next_year, :month => @next_month)%>
<table>
	<tr>
		<th>Sun</th>
		<th>Mon</th>
		<th>Tue</th>
		<th>Wed</th>
		<th>Thu</th>
		<th>Fri</th>
		<th>Sat</th>
	</tr>	
	<%=@str.html_safe%>
</table>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>